openapi: "3.0.0"
info:
  title: Cloud Assess
  version: 1.7.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /debug/trace:
    post:
      summary: Trace the impacts for a generic request
      operationId: trace
      requestBody:
        description: A generic request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraceRequestListDto'
      responses:
        '200':
          description: Trace response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceResponseListDto'
  /pools/assess:
    post:
      summary: Assess a collection of pools
      operationId: assessPools
      requestBody:
        description: Collection of pools to assess
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoolListDto'
      responses:
        '200':
          description: Assessment of pools
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolListAssessmentDto'
  /compute_resources/assess:
    post:
      summary: Assess a collection of compute resources (FU5)
      operationId: assessComputeResources
      requestBody:
        description: Collection of compute resources to assess
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputeResourceListDto'
      responses:
        '200':
          description: Assessment of compute resources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputeResourceListAssessmentDto'
  /virtual_machines/assess:
    post:
      summary: Assess a collection of virtual machines (FU6)
      operationId: assessVirtualMachines
      requestBody:
        description: Collection of virtual machines to assess
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualMachineListDto'
      responses:
        '200':
          description: Assessment of virtual machines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VirtualMachineListAssessmentDto'
  /storage_resources/assess:
    post:
      summary: Assess a collection of storage resources (FU7)
      operationId: assessStorageResources
      requestBody:
        description: Collection of storage resources to assess
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageResourceListDto'
      responses:
        '200':
          description: Assessment of storage resources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageResourceListAssessmentDto'

  /health:
    get:
      summary: Health endpoint
      operationId: health
      responses:
        '200':
          description: Healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatusDto'
components:
  schemas:
    PoolListAssessmentDto:
      type: object
      required:
        - pools
      properties:
        pools:
          type: array
          items:
            $ref: '#/components/schemas/PoolAssessmentDto'
    VirtualMachineListAssessmentDto:
      type: object
      required:
        - virtual_machines
      properties:
        virtual_machines:
          type: array
          items:
            $ref: '#/components/schemas/VirtualMachineAssessmentDto'
    PoolAssessmentDto:
      type: object
      required:
        - period
        - request
        - impacts
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        request:
          $ref: '#/components/schemas/PoolDto'
        impacts:
          $ref: '#/components/schemas/ImpactsDto'
    VirtualMachineAssessmentDto:
      type: object
      required:
        - period
        - request
        - impacts
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        request:
          $ref: '#/components/schemas/VirtualMachineDto'
        impacts:
          $ref: '#/components/schemas/ImpactsDto'
    QuantityDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          type: string
    ImpactsDto:
      type: object
      required:
        - ADPe
        - ADPf
        - AP
        - GWP
        - LU
        - ODP
        - PM
        - POCP
        - WU
        - CTUe
        - CTUh_c
        - CTUh_nc
        - Epf
        - Epm
        - Ept
        - IR
      properties:
        ADPe:
          $ref: '#/components/schemas/ImpactDto'
        ADPf:
          $ref: '#/components/schemas/ImpactDto'
        AP:
          $ref: '#/components/schemas/ImpactDto'
        GWP:
          $ref: '#/components/schemas/ImpactDto'
        LU:
          $ref: '#/components/schemas/ImpactDto'
        ODP:
          $ref: '#/components/schemas/ImpactDto'
        PM:
          $ref: '#/components/schemas/ImpactDto'
        POCP:
          $ref: '#/components/schemas/ImpactDto'
        WU:
          $ref: '#/components/schemas/ImpactDto'
        CTUe:
          $ref: '#/components/schemas/ImpactDto'
        CTUh_c:
          $ref: '#/components/schemas/ImpactDto'
        CTUh_nc:
          $ref: '#/components/schemas/ImpactDto'
        Epf:
          $ref: '#/components/schemas/ImpactDto'
        Epm:
          $ref: '#/components/schemas/ImpactDto'
        Ept:
          $ref: '#/components/schemas/ImpactDto'
        IR:
          $ref: '#/components/schemas/ImpactDto'
    ImpactDto:
      type: object
      required:
        - total
        - per_lc_step
      properties:
        total:
          $ref: '#/components/schemas/QuantityDto'
        per_lc_step:
          $ref: '#/components/schemas/ImpactPerLcStepDto'
    PoolDto:
      type: object
      required:
        - id
        - meta
      properties:
        id:
          type: string
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
    PoolListDto:
      type: object
      required:
        - period
        - pools
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        pools:
          type: array
          items:
            $ref: '#/components/schemas/PoolDto'
    VirtualMachineListDto:
      type: object
      required:
        - period
        - virtual_machines
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        virtual_machines:
          type: array
          items:
            $ref: '#/components/schemas/VirtualMachineDto'
    VirtualMachineDto:
      type: object
      required:
        - id
        - pool_id
        - quantity
        - ram
        - storage
        - vcpu
        - meta
      properties:
        id:
          type: string
        pool_id:
          type: string
        quantity:
          $ref: '#/components/schemas/QuantityDimensionlessDto'
        ram:
          $ref: '#/components/schemas/QuantityMemoryDto'
        storage:
          $ref: '#/components/schemas/QuantityMemoryDto'
        vcpu:
          $ref: '#/components/schemas/QuantityVCPUDto'
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
    QuantityVCPUDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/VCPUUnitsDto'
    QuantityTimeDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/TimeUnitsDto'
    QuantityMemoryDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/MemoryUnitsDto'
    QuantityDimensionlessDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/DimensionlessUnitsDto'
    VCPUUnitsDto:
      type: string
      enum:
        - vCPU
    DimensionlessUnitsDto:
      type: string
      enum:
        - u
    MemoryUnitsDto:
      type: string
      enum:
        - GB
        - TB
    TimeUnitsDto:
      type: string
      enum:
        - hour
    HealthStatusDto:
      type: object
      properties:
        status:
          type: string
          enum:
            - UP
    TraceRequestListDto:
      type: object
      required:
        - elements
      properties:
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
        globals:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ParameterDto'
        datasources:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/DatasourceDto'
        elements:
          type: array
          items:
            $ref: '#/components/schemas/TraceRequestDto'
    TraceRequestDto:
      type: object
      required:
        - requestId
        - demand
      properties:
        requestId:
          type: string
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
        maxDepth:
          type: integer
          default: -1
        demand:
          $ref: '#/components/schemas/DemandDto'
        globals:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ParameterDto'
        datasources:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/DatasourceDto'

    ErrorDto:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    TraceResponseListDto:
      type: object
      properties:
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
        elements:
          type: array
          items:
            $ref: '#/components/schemas/TraceResponseDto'

    TraceResponseDto:
      type: object
      properties:
        requestId:
          type: string
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
        trace:
          type: array
          items:
            $ref: '#/components/schemas/TraceResponseRowDto'
    TraceResponseRowDto:
      type: object
      required:
        - depth
      properties:
        depth:
          type: integer
        name:
          type: string
        processName:
          type: string
        params:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ParameterDto'
        labels:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ProcessLabelDto'
        compartment:
          type: string
        subCompartment:
          type: string
        supply:
          $ref: '#/components/schemas/QuantityDto'
        impacts:
          type: array
          items:
            $ref: '#/components/schemas/RawImpactDto'
    ParameterDto:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: ParameterValueDto
    ProcessLabelDto:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: string
    DatasourceDto:
      type: object
      required:
        - name
        - records
      properties:
        name:
          type: string
        records:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/RecordDto'
    RecordDto:
      type: object
      required:
        - elements
      properties:
        elements:
          type: array
          items:
            $ref: '#/components/schemas/EntryDto'
    EntryDto:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: EntryValueDto # string or number
    DemandDto:
      required:
        - quantity
        - productName
        - processName
      properties:
        productName:
          type: string
        quantity:
          $ref: '#/components/schemas/QuantityDto'
        processName:
          type: string
        params:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ParameterDto'
        labels:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ProcessLabelDto'
    ImpactPerLcStepDto:
      type: object
      required:
        - manufacturing
        - transport
        - use
        - end_of_life
      properties:
        manufacturing:
          $ref: '#/components/schemas/QuantityDto'
        transport:
          $ref: '#/components/schemas/QuantityDto'
        use:
          $ref: '#/components/schemas/QuantityDto'
        end_of_life:
          $ref: '#/components/schemas/QuantityDto'
    RawImpactDto:
      type: object
      properties:
        indicator:
          type: string
        value:
          $ref: '#/components/schemas/QuantityDto'
    ComputeResourceListDto:
      type: object
      required:
        - period
        - compute_resources
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        compute_resources:
          type: array
          items:
            $ref: '#/components/schemas/ComputeResourceDto'
    ComputeResourceDto:
      type: object
      required:
        - id
        - pool_id
        - quantity
        - vcpu
        - meta
      properties:
        id:
          type: string
        pool_id:
          type: string
        quantity:
          $ref: '#/components/schemas/QuantityDimensionlessDto'
        vcpu:
          $ref: '#/components/schemas/QuantityVCPUDto'
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
    ComputeResourceListAssessmentDto:
      type: object
      required:
        - compute_resources
      properties:
        compute_resources:
          type: array
          items:
            $ref: '#/components/schemas/ComputeResourceAssessmentDto'
    ComputeResourceAssessmentDto:
      type: object
      required:
        - period
        - request
        - impacts
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        request:
          $ref: '#/components/schemas/ComputeResourceDto'
        impacts:
          $ref: '#/components/schemas/ImpactsDto'
    StorageResourceListDto:
      type: object
      required:
        - period
        - storage_resources
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        storage_resources:
          type: array
          items:
            $ref: '#/components/schemas/StorageResourceDto'
    StorageResourceDto:
      type: object
      required:
        - id
        - pool_id
        - quantity
        - storage
        - vcpu
        - meta
      properties:
        id:
          type: string
        pool_id:
          type: string
        quantity:
          $ref: '#/components/schemas/QuantityDimensionlessDto'
        storage:
          $ref: '#/components/schemas/QuantityMemoryDto'
        vcpu:
          $ref: '#/components/schemas/QuantityVCPUDto'
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
    StorageResourceListAssessmentDto:
      type: object
      properties:
        storage_resources:
          type: array
          items:
            $ref: '#/components/schemas/StorageResourceAssessmentDto'
    StorageResourceAssessmentDto:
      type: object
      required:
        - period
        - request
        - impacts
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        request:
          $ref: '#/components/schemas/StorageResourceDto'
        impacts:
          $ref: '#/components/schemas/ImpactsDto'
