openapi: "3.0.0"
info:
  title: Cloud Assess
  version: 1.6.5
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /debug/trace:
    post:
      summary: Trace the impacts for a generic request
      operationId: trace
      requestBody:
        description: A generic request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraceRequestDto'
      responses:
        '200':
          description: Trace response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceResponseDto'
  /pools/assess:
    post:
      summary: Assess a collection of pools
      operationId: assessPools
      requestBody:
        description: Collection of pools to assess
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoolListDto'
      responses:
        '200':
          description: Assessment of pools
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolListAssessmentDto'
  /virtual_machines/assess:
    post:
      summary: Assess a collection of virtual machines
      operationId: assessVirtualMachines
      requestBody:
        description: Collection of virtual machines to assess
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualMachineListDto'
      responses:
        '200':
          description: Assessment of virtual machines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VirtualMachineListAssessmentDto'
  /health:
    get:
      summary: Health endpoint
      operationId: health
      responses:
        '200':
          description: Healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatusDto'
components:
  schemas:
    PoolListAssessmentDto:
      type: object
      required:
        - pools
      properties:
        pools:
          type: array
          items:
            $ref: '#/components/schemas/PoolAssessmentDto'
    VirtualMachineListAssessmentDto:
      type: object
      required:
        - virtual_machines
      properties:
        virtual_machines:
          type: array
          items:
            $ref: '#/components/schemas/VirtualMachineAssessmentDto'
    PoolAssessmentDto:
      type: object
      required:
        - period
        - request
        - impacts
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        request:
          $ref: '#/components/schemas/PoolDto'
        impacts:
          $ref: '#/components/schemas/ImpactsDto'
    VirtualMachineAssessmentDto:
      type: object
      required:
        - period
        - request
        - impacts
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        request:
          $ref: '#/components/schemas/VirtualMachineDto'
        impacts:
          $ref: '#/components/schemas/ImpactsDto'
    QuantityDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          type: string
    ImpactsDto:
      type: object
      required:
        - ADPe
        - ADPf
        - AP
        - GWP
        - LU
        - ODP
        - PM
        - POCP
        - WU
        - CTUe
        - CTUh_c
        - CTUh_nc
        - Epf
        - Epm
        - Ept
        - IR
      properties:
        ADPe:
          $ref: '#/components/schemas/ImpactDto'
        ADPf:
          $ref: '#/components/schemas/ImpactDto'
        AP:
          $ref: '#/components/schemas/ImpactDto'
        GWP:
          $ref: '#/components/schemas/ImpactDto'
        LU:
          $ref: '#/components/schemas/ImpactDto'
        ODP:
          $ref: '#/components/schemas/ImpactDto'
        PM:
          $ref: '#/components/schemas/ImpactDto'
        POCP:
          $ref: '#/components/schemas/ImpactDto'
        WU:
          $ref: '#/components/schemas/ImpactDto'
        CTUe:
          $ref: '#/components/schemas/ImpactDto'
        CTUh_c:
          $ref: '#/components/schemas/ImpactDto'
        CTUh_nc:
          $ref: '#/components/schemas/ImpactDto'
        Epf:
          $ref: '#/components/schemas/ImpactDto'
        Epm:
          $ref: '#/components/schemas/ImpactDto'
        Ept:
          $ref: '#/components/schemas/ImpactDto'
        IR:
          $ref: '#/components/schemas/ImpactDto'
    ImpactDto:
      type: object
      required:
        - total
      properties:
        total:
          $ref: '#/components/schemas/QuantityDto'
        # TODO: per lc step
    PoolDto:
      type: object
      required:
        - id
        - service_level
        - meta
      properties:
        id:
          type: string
        service_level:
          $ref: '#/components/schemas/QuantityDimensionlessDto'
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
    PoolListDto:
      type: object
      required:
        - period
        - pools
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        pools:
          type: array
          items:
            $ref: '#/components/schemas/PoolDto'
    VirtualMachineListDto:
      type: object
      required:
        - period
        - virtual_machines
      properties:
        period:
          $ref: '#/components/schemas/QuantityTimeDto'
        virtual_machines:
          type: array
          items:
            $ref: '#/components/schemas/VirtualMachineDto'
    VirtualMachineDto:
      type: object
      required:
        - id
        - pool_id
        - ram
        - storage
        - vcpu
        - meta
      properties:
        id:
          type: string
        pool_id:
          type: string
        ram:
          $ref: '#/components/schemas/QuantityMemoryDto'
        storage:
          $ref: '#/components/schemas/QuantityMemoryDto'
        vcpu:
          $ref: '#/components/schemas/QuantityVCPUDto'
        meta:
          type: object
          default: { }
          additionalProperties:
            type: string
    QuantityVCPUDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/VCPUUnitsDto'
    QuantityTimeDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/TimeUnitsDto'
    QuantityMemoryDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/MemoryUnitsDto'
    QuantityDimensionlessDto:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          format: double
        unit:
          $ref: '#/components/schemas/DimensionlessUnitsDto'
    VCPUUnitsDto:
      type: string
      enum:
        - vCPU
    DimensionlessUnitsDto:
      type: string
      enum:
        - u
    MemoryUnitsDto:
      type: string
      enum:
        - GB
        - TB
    TimeUnitsDto:
      type: string
      enum:
        - hour
    HealthStatusDto:
      type: object
      properties:
        status:
          type: string
          enum:
            - UP
    TraceRequestDto:
      type: object
      properties:
        requestId:
          type: string
        options:
          $ref: '#/components/schemas/TraceRequestOptionsDto'
        product:
          type: object
          properties:
            quantity:
              $ref: '#/components/schemas/QuantityDto'
            name:
              type: string
        fromProcess:
          type: object
          properties:
            name:
              type: string
            params:
              type: array
              items:
                $ref: '#/components/schemas/ParameterDto'
            labels:
              type: array
              items:
                $ref: '#/components/schemas/ProcessLabelDto'
        globals:
          type: array
          items:
            $ref: '#/components/schemas/ParameterDto'
        datasources:
          type: array
          items:
            $ref: '#/components/schemas/DatasourceDto'


    TraceResponseDto:
      type: object
      properties:
        requestId:
          type: string
        trace:
          type: array
          items:
            $ref: '#/components/schemas/TraceResponseRowDto'
    TraceResponseRowDto:
      type: object
      properties:
        depth:
          type: integer
        product:
          type: object
          properties:
            quantity:
              $ref: '#/components/schemas/QuantityDto'
            name:
              type: string
        fromProcess:
          type: object
          properties:
            name:
              type: string
            params:
              type: array
              items:
                $ref: '#/components/schemas/ParameterDto'
            labels:
              type: array
              items:
                $ref: '#/components/schemas/ProcessLabelDto'
        impacts:
          type: array
          items:
            $ref: '#/components/schemas/ImpactsDto'


    ParameterDto:
      type: object
      properties:
        name:
          type: string
        value:
          $ref: '#/components/schemas/QuantityDto'

    ProcessLabelDto:
      type: object
      properties:
        name:
          type: string
        value:
          type: string

    DatasourceDto:
      type: object
      properties:
        name:
          type: string
        content:
          type: array
          items:
            $ref: '#/components/schemas/DatasourceRowDto'
    DatasourceRowDto:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/DatasourceCellDto'
    DatasourceCellDto:
      type: object
      properties:
        name:
          type: string
        value:
          oneOf:
            - type: string
            - type: number
    TraceRequestOptionsDto:
      type: object
      properties:
        useDefaultDatasourceIfNotProvided:
          type: boolean
          default: false

