/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordDto } from './RecordDto';
import {
    RecordDtoFromJSON,
    RecordDtoFromJSONTyped,
    RecordDtoToJSON,
} from './RecordDto';

/**
 * 
 * @export
 * @interface DatasourceDto
 */
export interface DatasourceDto {
    /**
     * 
     * @type {string}
     * @memberof DatasourceDto
     */
    name: string;
    /**
     * 
     * @type {Array<RecordDto>}
     * @memberof DatasourceDto
     */
    records: Array<RecordDto>;
}

/**
 * Check if a given object implements the DatasourceDto interface.
 */
export function instanceOfDatasourceDto(value: object): value is DatasourceDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function DatasourceDtoFromJSON(json: any): DatasourceDto {
    return DatasourceDtoFromJSONTyped(json, false);
}

export function DatasourceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasourceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'records': ((json['records'] as Array<any>).map(RecordDtoFromJSON)),
    };
}

export function DatasourceDtoToJSON(value?: DatasourceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'records': ((value['records'] as Array<any>).map(RecordDtoToJSON)),
    };
}

