/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuantityDto } from './QuantityDto';
import {
    QuantityDtoFromJSON,
    QuantityDtoFromJSONTyped,
    QuantityDtoToJSON,
} from './QuantityDto';
import type { ProcessLabelDto } from './ProcessLabelDto';
import {
    ProcessLabelDtoFromJSON,
    ProcessLabelDtoFromJSONTyped,
    ProcessLabelDtoToJSON,
} from './ProcessLabelDto';
import type { ParameterDto } from './ParameterDto';
import {
    ParameterDtoFromJSON,
    ParameterDtoFromJSONTyped,
    ParameterDtoToJSON,
} from './ParameterDto';

/**
 * 
 * @export
 * @interface DemandDto
 */
export interface DemandDto {
    /**
     * 
     * @type {string}
     * @memberof DemandDto
     */
    productName: string;
    /**
     * 
     * @type {QuantityDto}
     * @memberof DemandDto
     */
    quantity: QuantityDto;
    /**
     * 
     * @type {string}
     * @memberof DemandDto
     */
    processName: string;
    /**
     * 
     * @type {Array<ParameterDto>}
     * @memberof DemandDto
     */
    params?: Array<ParameterDto>;
    /**
     * 
     * @type {Array<ProcessLabelDto>}
     * @memberof DemandDto
     */
    labels?: Array<ProcessLabelDto>;
}

/**
 * Check if a given object implements the DemandDto interface.
 */
export function instanceOfDemandDto(value: object): value is DemandDto {
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('processName' in value) || value['processName'] === undefined) return false;
    return true;
}

export function DemandDtoFromJSON(json: any): DemandDto {
    return DemandDtoFromJSONTyped(json, false);
}

export function DemandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productName': json['productName'],
        'quantity': QuantityDtoFromJSON(json['quantity']),
        'processName': json['processName'],
        'params': json['params'] == null ? undefined : ((json['params'] as Array<any>).map(ParameterDtoFromJSON)),
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(ProcessLabelDtoFromJSON)),
    };
}

export function DemandDtoToJSON(value?: DemandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'productName': value['productName'],
        'quantity': QuantityDtoToJSON(value['quantity']),
        'processName': value['processName'],
        'params': value['params'] == null ? undefined : ((value['params'] as Array<any>).map(ParameterDtoToJSON)),
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(ProcessLabelDtoToJSON)),
    };
}

