/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DimensionlessUnitsDto = {
    U: 'u'
} as const;
export type DimensionlessUnitsDto = typeof DimensionlessUnitsDto[keyof typeof DimensionlessUnitsDto];


export function instanceOfDimensionlessUnitsDto(value: any): boolean {
    for (const key in DimensionlessUnitsDto) {
        if (Object.prototype.hasOwnProperty.call(DimensionlessUnitsDto, key)) {
            if (DimensionlessUnitsDto[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DimensionlessUnitsDtoFromJSON(json: any): DimensionlessUnitsDto {
    return DimensionlessUnitsDtoFromJSONTyped(json, false);
}

export function DimensionlessUnitsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DimensionlessUnitsDto {
    return json as DimensionlessUnitsDto;
}

export function DimensionlessUnitsDtoToJSON(value?: DimensionlessUnitsDto | null): any {
    return value as any;
}

