/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryValueDto } from './EntryValueDto';
import {
    EntryValueDtoFromJSON,
    EntryValueDtoFromJSONTyped,
    EntryValueDtoToJSON,
} from './EntryValueDto';

/**
 * 
 * @export
 * @interface EntryDto
 */
export interface EntryDto {
    /**
     * 
     * @type {string}
     * @memberof EntryDto
     */
    name: string;
    /**
     * 
     * @type {EntryValueDto}
     * @memberof EntryDto
     */
    value: EntryValueDto;
}

/**
 * Check if a given object implements the EntryDto interface.
 */
export function instanceOfEntryDto(value: object): value is EntryDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EntryDtoFromJSON(json: any): EntryDto {
    return EntryDtoFromJSONTyped(json, false);
}

export function EntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': EntryValueDtoFromJSON(json['value']),
    };
}

export function EntryDtoToJSON(value?: EntryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': EntryValueDtoToJSON(value['value']),
    };
}

