/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthStatusDto
 */
export interface HealthStatusDto {
    /**
     * 
     * @type {string}
     * @memberof HealthStatusDto
     */
    status?: HealthStatusDtoStatusEnum;
}


/**
 * @export
 */
export const HealthStatusDtoStatusEnum = {
    Up: 'UP'
} as const;
export type HealthStatusDtoStatusEnum = typeof HealthStatusDtoStatusEnum[keyof typeof HealthStatusDtoStatusEnum];


/**
 * Check if a given object implements the HealthStatusDto interface.
 */
export function instanceOfHealthStatusDto(value: object): value is HealthStatusDto {
    return true;
}

export function HealthStatusDtoFromJSON(json: any): HealthStatusDto {
    return HealthStatusDtoFromJSONTyped(json, false);
}

export function HealthStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HealthStatusDtoToJSON(value?: HealthStatusDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

