/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuantityDto } from './QuantityDto';
import {
    QuantityDtoFromJSON,
    QuantityDtoFromJSONTyped,
    QuantityDtoToJSON,
} from './QuantityDto';

/**
 * 
 * @export
 * @interface ImpactDto
 */
export interface ImpactDto {
    /**
     * 
     * @type {QuantityDto}
     * @memberof ImpactDto
     */
    total: QuantityDto;
}

/**
 * Check if a given object implements the ImpactDto interface.
 */
export function instanceOfImpactDto(value: object): value is ImpactDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ImpactDtoFromJSON(json: any): ImpactDto {
    return ImpactDtoFromJSONTyped(json, false);
}

export function ImpactDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': QuantityDtoFromJSON(json['total']),
    };
}

export function ImpactDtoToJSON(value?: ImpactDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': QuantityDtoToJSON(value['total']),
    };
}

