/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImpactDto } from './ImpactDto';
import {
    ImpactDtoFromJSON,
    ImpactDtoFromJSONTyped,
    ImpactDtoToJSON,
} from './ImpactDto';

/**
 * 
 * @export
 * @interface ImpactsDto
 */
export interface ImpactsDto {
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    aDPe: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    aDPf: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    aP: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    gWP: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    lU: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    oDP: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    pM: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    pOCP: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    wU: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    cTUe: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    cTUhC: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    cTUhNc: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    epf: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    epm: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    ept: ImpactDto;
    /**
     * 
     * @type {ImpactDto}
     * @memberof ImpactsDto
     */
    iR: ImpactDto;
}

/**
 * Check if a given object implements the ImpactsDto interface.
 */
export function instanceOfImpactsDto(value: object): value is ImpactsDto {
    if (!('aDPe' in value) || value['aDPe'] === undefined) return false;
    if (!('aDPf' in value) || value['aDPf'] === undefined) return false;
    if (!('aP' in value) || value['aP'] === undefined) return false;
    if (!('gWP' in value) || value['gWP'] === undefined) return false;
    if (!('lU' in value) || value['lU'] === undefined) return false;
    if (!('oDP' in value) || value['oDP'] === undefined) return false;
    if (!('pM' in value) || value['pM'] === undefined) return false;
    if (!('pOCP' in value) || value['pOCP'] === undefined) return false;
    if (!('wU' in value) || value['wU'] === undefined) return false;
    if (!('cTUe' in value) || value['cTUe'] === undefined) return false;
    if (!('cTUhC' in value) || value['cTUhC'] === undefined) return false;
    if (!('cTUhNc' in value) || value['cTUhNc'] === undefined) return false;
    if (!('epf' in value) || value['epf'] === undefined) return false;
    if (!('epm' in value) || value['epm'] === undefined) return false;
    if (!('ept' in value) || value['ept'] === undefined) return false;
    if (!('iR' in value) || value['iR'] === undefined) return false;
    return true;
}

export function ImpactsDtoFromJSON(json: any): ImpactsDto {
    return ImpactsDtoFromJSONTyped(json, false);
}

export function ImpactsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'aDPe': ImpactDtoFromJSON(json['ADPe']),
        'aDPf': ImpactDtoFromJSON(json['ADPf']),
        'aP': ImpactDtoFromJSON(json['AP']),
        'gWP': ImpactDtoFromJSON(json['GWP']),
        'lU': ImpactDtoFromJSON(json['LU']),
        'oDP': ImpactDtoFromJSON(json['ODP']),
        'pM': ImpactDtoFromJSON(json['PM']),
        'pOCP': ImpactDtoFromJSON(json['POCP']),
        'wU': ImpactDtoFromJSON(json['WU']),
        'cTUe': ImpactDtoFromJSON(json['CTUe']),
        'cTUhC': ImpactDtoFromJSON(json['CTUh_c']),
        'cTUhNc': ImpactDtoFromJSON(json['CTUh_nc']),
        'epf': ImpactDtoFromJSON(json['Epf']),
        'epm': ImpactDtoFromJSON(json['Epm']),
        'ept': ImpactDtoFromJSON(json['Ept']),
        'iR': ImpactDtoFromJSON(json['IR']),
    };
}

export function ImpactsDtoToJSON(value?: ImpactsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ADPe': ImpactDtoToJSON(value['aDPe']),
        'ADPf': ImpactDtoToJSON(value['aDPf']),
        'AP': ImpactDtoToJSON(value['aP']),
        'GWP': ImpactDtoToJSON(value['gWP']),
        'LU': ImpactDtoToJSON(value['lU']),
        'ODP': ImpactDtoToJSON(value['oDP']),
        'PM': ImpactDtoToJSON(value['pM']),
        'POCP': ImpactDtoToJSON(value['pOCP']),
        'WU': ImpactDtoToJSON(value['wU']),
        'CTUe': ImpactDtoToJSON(value['cTUe']),
        'CTUh_c': ImpactDtoToJSON(value['cTUhC']),
        'CTUh_nc': ImpactDtoToJSON(value['cTUhNc']),
        'Epf': ImpactDtoToJSON(value['epf']),
        'Epm': ImpactDtoToJSON(value['epm']),
        'Ept': ImpactDtoToJSON(value['ept']),
        'IR': ImpactDtoToJSON(value['iR']),
    };
}

