/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MemoryUnitsDto = {
    Gb: 'GB',
    Tb: 'TB'
} as const;
export type MemoryUnitsDto = typeof MemoryUnitsDto[keyof typeof MemoryUnitsDto];


export function MemoryUnitsDtoFromJSON(json: any): MemoryUnitsDto {
    return MemoryUnitsDtoFromJSONTyped(json, false);
}

export function MemoryUnitsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryUnitsDto {
    return json as MemoryUnitsDto;
}

export function MemoryUnitsDtoToJSON(value?: MemoryUnitsDto | null): any {
    return value as any;
}

