/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptionsDto
 */
export interface OptionsDto {
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDto
     */
    useDefaultDatasourceIfNotProvided?: boolean;
}

/**
 * Check if a given object implements the OptionsDto interface.
 */
export function instanceOfOptionsDto(value: object): value is OptionsDto {
    return true;
}

export function OptionsDtoFromJSON(json: any): OptionsDto {
    return OptionsDtoFromJSONTyped(json, false);
}

export function OptionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'useDefaultDatasourceIfNotProvided': json['useDefaultDatasourceIfNotProvided'] == null ? undefined : json['useDefaultDatasourceIfNotProvided'],
    };
}

export function OptionsDtoToJSON(value?: OptionsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'useDefaultDatasourceIfNotProvided': value['useDefaultDatasourceIfNotProvided'],
    };
}

