/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParameterValueDto } from './ParameterValueDto';
import {
    ParameterValueDtoFromJSON,
    ParameterValueDtoFromJSONTyped,
    ParameterValueDtoToJSON,
} from './ParameterValueDto';

/**
 * 
 * @export
 * @interface ParameterDto
 */
export interface ParameterDto {
    /**
     * 
     * @type {string}
     * @memberof ParameterDto
     */
    name: string;
    /**
     * 
     * @type {ParameterValueDto}
     * @memberof ParameterDto
     */
    value: ParameterValueDto;
}

/**
 * Check if a given object implements the ParameterDto interface.
 */
export function instanceOfParameterDto(value: object): value is ParameterDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ParameterDtoFromJSON(json: any): ParameterDto {
    return ParameterDtoFromJSONTyped(json, false);
}

export function ParameterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': ParameterValueDtoFromJSON(json['value']),
    };
}

export function ParameterDtoToJSON(value?: ParameterDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': ParameterValueDtoToJSON(value['value']),
    };
}

