/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PoolDto } from './PoolDto';
import {
    PoolDtoFromJSON,
    PoolDtoFromJSONTyped,
    PoolDtoToJSON,
} from './PoolDto';
import type { QuantityTimeDto } from './QuantityTimeDto';
import {
    QuantityTimeDtoFromJSON,
    QuantityTimeDtoFromJSONTyped,
    QuantityTimeDtoToJSON,
} from './QuantityTimeDto';

/**
 * 
 * @export
 * @interface PoolListDto
 */
export interface PoolListDto {
    /**
     * 
     * @type {QuantityTimeDto}
     * @memberof PoolListDto
     */
    period: QuantityTimeDto;
    /**
     * 
     * @type {Array<PoolDto>}
     * @memberof PoolListDto
     */
    pools: Array<PoolDto>;
}

/**
 * Check if a given object implements the PoolListDto interface.
 */
export function instanceOfPoolListDto(value: object): value is PoolListDto {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('pools' in value) || value['pools'] === undefined) return false;
    return true;
}

export function PoolListDtoFromJSON(json: any): PoolListDto {
    return PoolListDtoFromJSONTyped(json, false);
}

export function PoolListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoolListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'period': QuantityTimeDtoFromJSON(json['period']),
        'pools': ((json['pools'] as Array<any>).map(PoolDtoFromJSON)),
    };
}

export function PoolListDtoToJSON(value?: PoolListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'period': QuantityTimeDtoToJSON(value['period']),
        'pools': ((value['pools'] as Array<any>).map(PoolDtoToJSON)),
    };
}

