/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessLabelDto
 */
export interface ProcessLabelDto {
    /**
     * 
     * @type {string}
     * @memberof ProcessLabelDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessLabelDto
     */
    value: string;
}

/**
 * Check if a given object implements the ProcessLabelDto interface.
 */
export function instanceOfProcessLabelDto(value: object): value is ProcessLabelDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ProcessLabelDtoFromJSON(json: any): ProcessLabelDto {
    return ProcessLabelDtoFromJSONTyped(json, false);
}

export function ProcessLabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessLabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function ProcessLabelDtoToJSON(value?: ProcessLabelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

