/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeUnitsDto } from './TimeUnitsDto';
import {
    TimeUnitsDtoFromJSON,
    TimeUnitsDtoFromJSONTyped,
    TimeUnitsDtoToJSON,
} from './TimeUnitsDto';

/**
 * 
 * @export
 * @interface QuantityTimeDto
 */
export interface QuantityTimeDto {
    /**
     * 
     * @type {number}
     * @memberof QuantityTimeDto
     */
    amount: number;
    /**
     * 
     * @type {TimeUnitsDto}
     * @memberof QuantityTimeDto
     */
    unit: TimeUnitsDto;
}

/**
 * Check if a given object implements the QuantityTimeDto interface.
 */
export function instanceOfQuantityTimeDto(value: object): value is QuantityTimeDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function QuantityTimeDtoFromJSON(json: any): QuantityTimeDto {
    return QuantityTimeDtoFromJSONTyped(json, false);
}

export function QuantityTimeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuantityTimeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'unit': TimeUnitsDtoFromJSON(json['unit']),
    };
}

export function QuantityTimeDtoToJSON(value?: QuantityTimeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'unit': TimeUnitsDtoToJSON(value['unit']),
    };
}

