/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DimensionlessUnitsDto } from './DimensionlessUnitsDto';
import {
    DimensionlessUnitsDtoFromJSON,
    DimensionlessUnitsDtoFromJSONTyped,
    DimensionlessUnitsDtoToJSON,
} from './DimensionlessUnitsDto';

/**
 * 
 * @export
 * @interface QuantityDimensionlessDto
 */
export interface QuantityDimensionlessDto {
    /**
     * 
     * @type {number}
     * @memberof QuantityDimensionlessDto
     */
    amount: number;
    /**
     * 
     * @type {DimensionlessUnitsDto}
     * @memberof QuantityDimensionlessDto
     */
    unit: DimensionlessUnitsDto;
}

/**
 * Check if a given object implements the QuantityDimensionlessDto interface.
 */
export function instanceOfQuantityDimensionlessDto(value: object): value is QuantityDimensionlessDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function QuantityDimensionlessDtoFromJSON(json: any): QuantityDimensionlessDto {
    return QuantityDimensionlessDtoFromJSONTyped(json, false);
}

export function QuantityDimensionlessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuantityDimensionlessDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'unit': DimensionlessUnitsDtoFromJSON(json['unit']),
    };
}

export function QuantityDimensionlessDtoToJSON(value?: QuantityDimensionlessDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'unit': DimensionlessUnitsDtoToJSON(value['unit']),
    };
}

