/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VCPUUnitsDto } from './VCPUUnitsDto';
import {
    VCPUUnitsDtoFromJSON,
    VCPUUnitsDtoFromJSONTyped,
    VCPUUnitsDtoToJSON,
} from './VCPUUnitsDto';

/**
 * 
 * @export
 * @interface QuantityVCPUDto
 */
export interface QuantityVCPUDto {
    /**
     * 
     * @type {number}
     * @memberof QuantityVCPUDto
     */
    amount: number;
    /**
     * 
     * @type {VCPUUnitsDto}
     * @memberof QuantityVCPUDto
     */
    unit: VCPUUnitsDto;
}

/**
 * Check if a given object implements the QuantityVCPUDto interface.
 */
export function instanceOfQuantityVCPUDto(value: object): value is QuantityVCPUDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function QuantityVCPUDtoFromJSON(json: any): QuantityVCPUDto {
    return QuantityVCPUDtoFromJSONTyped(json, false);
}

export function QuantityVCPUDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuantityVCPUDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'unit': VCPUUnitsDtoFromJSON(json['unit']),
    };
}

export function QuantityVCPUDtoToJSON(value?: QuantityVCPUDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'unit': VCPUUnitsDtoToJSON(value['unit']),
    };
}

