/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuantityDto
 */
export interface QuantityDto {
    /**
     * 
     * @type {number}
     * @memberof QuantityDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof QuantityDto
     */
    unit: string;
}

/**
 * Check if a given object implements the QuantityDto interface.
 */
export function instanceOfQuantityDto(value: object): value is QuantityDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function QuantityDtoFromJSON(json: any): QuantityDto {
    return QuantityDtoFromJSONTyped(json, false);
}

export function QuantityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuantityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'unit': json['unit'],
    };
}

export function QuantityDtoToJSON(value?: QuantityDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'unit': value['unit'],
    };
}

