/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryDto } from './EntryDto';
import {
    EntryDtoFromJSON,
    EntryDtoFromJSONTyped,
    EntryDtoToJSON,
} from './EntryDto';

/**
 * 
 * @export
 * @interface RecordDto
 */
export interface RecordDto {
    /**
     * 
     * @type {Array<EntryDto>}
     * @memberof RecordDto
     */
    elements: Array<EntryDto>;
}

/**
 * Check if a given object implements the RecordDto interface.
 */
export function instanceOfRecordDto(value: object): value is RecordDto {
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function RecordDtoFromJSON(json: any): RecordDto {
    return RecordDtoFromJSONTyped(json, false);
}

export function RecordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': ((json['elements'] as Array<any>).map(EntryDtoFromJSON)),
    };
}

export function RecordDtoToJSON(value?: RecordDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'elements': ((value['elements'] as Array<any>).map(EntryDtoToJSON)),
    };
}

