/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TimeUnitsDto = {
    Hour: 'hour'
} as const;
export type TimeUnitsDto = typeof TimeUnitsDto[keyof typeof TimeUnitsDto];


export function TimeUnitsDtoFromJSON(json: any): TimeUnitsDto {
    return TimeUnitsDtoFromJSONTyped(json, false);
}

export function TimeUnitsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeUnitsDto {
    return json as TimeUnitsDto;
}

export function TimeUnitsDtoToJSON(value?: TimeUnitsDto | null): any {
    return value as any;
}

