/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraceResponseDto } from './TraceResponseDto';
import {
    TraceResponseDtoFromJSON,
    TraceResponseDtoFromJSONTyped,
    TraceResponseDtoToJSON,
} from './TraceResponseDto';

/**
 * 
 * @export
 * @interface TraceResponseListDto
 */
export interface TraceResponseListDto {
    /**
     * 
     * @type {Array<TraceResponseDto>}
     * @memberof TraceResponseListDto
     */
    elements?: Array<TraceResponseDto>;
}

/**
 * Check if a given object implements the TraceResponseListDto interface.
 */
export function instanceOfTraceResponseListDto(value: object): value is TraceResponseListDto {
    return true;
}

export function TraceResponseListDtoFromJSON(json: any): TraceResponseListDto {
    return TraceResponseListDtoFromJSONTyped(json, false);
}

export function TraceResponseListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceResponseListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': json['elements'] == null ? undefined : ((json['elements'] as Array<any>).map(TraceResponseDtoFromJSON)),
    };
}

export function TraceResponseListDtoToJSON(value?: TraceResponseListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'elements': value['elements'] == null ? undefined : ((value['elements'] as Array<any>).map(TraceResponseDtoToJSON)),
    };
}

