/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraceResponseRowDto } from './TraceResponseRowDto';
import {
    TraceResponseRowDtoFromJSON,
    TraceResponseRowDtoFromJSONTyped,
    TraceResponseRowDtoToJSON,
} from './TraceResponseRowDto';

/**
 * 
 * @export
 * @interface TraceResponseDto
 */
export interface TraceResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TraceResponseDto
     */
    requestId?: string;
    /**
     * 
     * @type {Array<TraceResponseRowDto>}
     * @memberof TraceResponseDto
     */
    trace?: Array<TraceResponseRowDto>;
}

/**
 * Check if a given object implements the TraceResponseDto interface.
 */
export function instanceOfTraceResponseDto(value: object): value is TraceResponseDto {
    return true;
}

export function TraceResponseDtoFromJSON(json: any): TraceResponseDto {
    return TraceResponseDtoFromJSONTyped(json, false);
}

export function TraceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'trace': json['trace'] == null ? undefined : ((json['trace'] as Array<any>).map(TraceResponseRowDtoFromJSON)),
    };
}

export function TraceResponseDtoToJSON(value?: TraceResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'requestId': value['requestId'],
        'trace': value['trace'] == null ? undefined : ((value['trace'] as Array<any>).map(TraceResponseRowDtoToJSON)),
    };
}

