/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraceRequestDto } from './TraceRequestDto';
import {
    TraceRequestDtoFromJSON,
    TraceRequestDtoFromJSONTyped,
    TraceRequestDtoToJSON,
} from './TraceRequestDto';

/**
 * 
 * @export
 * @interface TraceRequestListDto
 */
export interface TraceRequestListDto {
    /**
     * 
     * @type {Array<TraceRequestDto>}
     * @memberof TraceRequestListDto
     */
    elements: Array<TraceRequestDto>;
}

/**
 * Check if a given object implements the TraceRequestListDto interface.
 */
export function instanceOfTraceRequestListDto(value: object): value is TraceRequestListDto {
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function TraceRequestListDtoFromJSON(json: any): TraceRequestListDto {
    return TraceRequestListDtoFromJSONTyped(json, false);
}

export function TraceRequestListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceRequestListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': ((json['elements'] as Array<any>).map(TraceRequestDtoFromJSON)),
    };
}

export function TraceRequestListDtoToJSON(value?: TraceRequestListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'elements': ((value['elements'] as Array<any>).map(TraceRequestDtoToJSON)),
    };
}

