/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuantityDto } from './QuantityDto';
import {
    QuantityDtoFromJSON,
    QuantityDtoFromJSONTyped,
    QuantityDtoToJSON,
} from './QuantityDto';
import type { ProcessLabelDto } from './ProcessLabelDto';
import {
    ProcessLabelDtoFromJSON,
    ProcessLabelDtoFromJSONTyped,
    ProcessLabelDtoToJSON,
} from './ProcessLabelDto';
import type { ImpactsDto } from './ImpactsDto';
import {
    ImpactsDtoFromJSON,
    ImpactsDtoFromJSONTyped,
    ImpactsDtoToJSON,
} from './ImpactsDto';
import type { ParameterDto } from './ParameterDto';
import {
    ParameterDtoFromJSON,
    ParameterDtoFromJSONTyped,
    ParameterDtoToJSON,
} from './ParameterDto';

/**
 * 
 * @export
 * @interface TraceResponseRowDto
 */
export interface TraceResponseRowDto {
    /**
     * 
     * @type {number}
     * @memberof TraceResponseRowDto
     */
    depth: number;
    /**
     * 
     * @type {string}
     * @memberof TraceResponseRowDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TraceResponseRowDto
     */
    processName?: string;
    /**
     * 
     * @type {Array<ParameterDto>}
     * @memberof TraceResponseRowDto
     */
    params?: Array<ParameterDto>;
    /**
     * 
     * @type {Array<ProcessLabelDto>}
     * @memberof TraceResponseRowDto
     */
    labels?: Array<ProcessLabelDto>;
    /**
     * 
     * @type {string}
     * @memberof TraceResponseRowDto
     */
    compartment?: string;
    /**
     * 
     * @type {string}
     * @memberof TraceResponseRowDto
     */
    subCompartment?: string;
    /**
     * 
     * @type {QuantityDto}
     * @memberof TraceResponseRowDto
     */
    supply?: QuantityDto;
    /**
     * 
     * @type {ImpactsDto}
     * @memberof TraceResponseRowDto
     */
    impacts?: ImpactsDto;
}

/**
 * Check if a given object implements the TraceResponseRowDto interface.
 */
export function instanceOfTraceResponseRowDto(value: object): value is TraceResponseRowDto {
    if (!('depth' in value) || value['depth'] === undefined) return false;
    return true;
}

export function TraceResponseRowDtoFromJSON(json: any): TraceResponseRowDto {
    return TraceResponseRowDtoFromJSONTyped(json, false);
}

export function TraceResponseRowDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceResponseRowDto {
    if (json == null) {
        return json;
    }
    return {
        
        'depth': json['depth'],
        'name': json['name'] == null ? undefined : json['name'],
        'processName': json['processName'] == null ? undefined : json['processName'],
        'params': json['params'] == null ? undefined : ((json['params'] as Array<any>).map(ParameterDtoFromJSON)),
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(ProcessLabelDtoFromJSON)),
        'compartment': json['compartment'] == null ? undefined : json['compartment'],
        'subCompartment': json['subCompartment'] == null ? undefined : json['subCompartment'],
        'supply': json['supply'] == null ? undefined : QuantityDtoFromJSON(json['supply']),
        'impacts': json['impacts'] == null ? undefined : ImpactsDtoFromJSON(json['impacts']),
    };
}

export function TraceResponseRowDtoToJSON(value?: TraceResponseRowDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'depth': value['depth'],
        'name': value['name'],
        'processName': value['processName'],
        'params': value['params'] == null ? undefined : ((value['params'] as Array<any>).map(ParameterDtoToJSON)),
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(ProcessLabelDtoToJSON)),
        'compartment': value['compartment'],
        'subCompartment': value['subCompartment'],
        'supply': QuantityDtoToJSON(value['supply']),
        'impacts': ImpactsDtoToJSON(value['impacts']),
    };
}

