/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VirtualMachineDto } from './VirtualMachineDto';
import {
    VirtualMachineDtoFromJSON,
    VirtualMachineDtoFromJSONTyped,
    VirtualMachineDtoToJSON,
} from './VirtualMachineDto';
import type { QuantityTimeDto } from './QuantityTimeDto';
import {
    QuantityTimeDtoFromJSON,
    QuantityTimeDtoFromJSONTyped,
    QuantityTimeDtoToJSON,
} from './QuantityTimeDto';
import type { ImpactsDto } from './ImpactsDto';
import {
    ImpactsDtoFromJSON,
    ImpactsDtoFromJSONTyped,
    ImpactsDtoToJSON,
} from './ImpactsDto';

/**
 * 
 * @export
 * @interface VirtualMachineAssessmentDto
 */
export interface VirtualMachineAssessmentDto {
    /**
     * 
     * @type {QuantityTimeDto}
     * @memberof VirtualMachineAssessmentDto
     */
    period: QuantityTimeDto;
    /**
     * 
     * @type {VirtualMachineDto}
     * @memberof VirtualMachineAssessmentDto
     */
    request: VirtualMachineDto;
    /**
     * 
     * @type {ImpactsDto}
     * @memberof VirtualMachineAssessmentDto
     */
    impacts: ImpactsDto;
}

/**
 * Check if a given object implements the VirtualMachineAssessmentDto interface.
 */
export function instanceOfVirtualMachineAssessmentDto(value: object): value is VirtualMachineAssessmentDto {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('impacts' in value) || value['impacts'] === undefined) return false;
    return true;
}

export function VirtualMachineAssessmentDtoFromJSON(json: any): VirtualMachineAssessmentDto {
    return VirtualMachineAssessmentDtoFromJSONTyped(json, false);
}

export function VirtualMachineAssessmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualMachineAssessmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'period': QuantityTimeDtoFromJSON(json['period']),
        'request': VirtualMachineDtoFromJSON(json['request']),
        'impacts': ImpactsDtoFromJSON(json['impacts']),
    };
}

export function VirtualMachineAssessmentDtoToJSON(value?: VirtualMachineAssessmentDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'period': QuantityTimeDtoToJSON(value['period']),
        'request': VirtualMachineDtoToJSON(value['request']),
        'impacts': ImpactsDtoToJSON(value['impacts']),
    };
}

