/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VirtualMachineDto } from './VirtualMachineDto';
import {
    VirtualMachineDtoFromJSON,
    VirtualMachineDtoFromJSONTyped,
    VirtualMachineDtoToJSON,
} from './VirtualMachineDto';
import type { QuantityTimeDto } from './QuantityTimeDto';
import {
    QuantityTimeDtoFromJSON,
    QuantityTimeDtoFromJSONTyped,
    QuantityTimeDtoToJSON,
} from './QuantityTimeDto';

/**
 * 
 * @export
 * @interface VirtualMachineListDto
 */
export interface VirtualMachineListDto {
    /**
     * 
     * @type {QuantityTimeDto}
     * @memberof VirtualMachineListDto
     */
    period: QuantityTimeDto;
    /**
     * 
     * @type {Array<VirtualMachineDto>}
     * @memberof VirtualMachineListDto
     */
    virtualMachines: Array<VirtualMachineDto>;
}

/**
 * Check if a given object implements the VirtualMachineListDto interface.
 */
export function instanceOfVirtualMachineListDto(value: object): value is VirtualMachineListDto {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('virtualMachines' in value) || value['virtualMachines'] === undefined) return false;
    return true;
}

export function VirtualMachineListDtoFromJSON(json: any): VirtualMachineListDto {
    return VirtualMachineListDtoFromJSONTyped(json, false);
}

export function VirtualMachineListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualMachineListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'period': QuantityTimeDtoFromJSON(json['period']),
        'virtualMachines': ((json['virtual_machines'] as Array<any>).map(VirtualMachineDtoFromJSON)),
    };
}

export function VirtualMachineListDtoToJSON(value?: VirtualMachineListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'period': QuantityTimeDtoToJSON(value['period']),
        'virtual_machines': ((value['virtualMachines'] as Array<any>).map(VirtualMachineDtoToJSON)),
    };
}

