/* tslint:disable */
/* eslint-disable */
/**
 * Cloud Assess
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuantityVCPUDto } from './QuantityVCPUDto';
import {
    QuantityVCPUDtoFromJSON,
    QuantityVCPUDtoFromJSONTyped,
    QuantityVCPUDtoToJSON,
} from './QuantityVCPUDto';
import type { QuantityMemoryDto } from './QuantityMemoryDto';
import {
    QuantityMemoryDtoFromJSON,
    QuantityMemoryDtoFromJSONTyped,
    QuantityMemoryDtoToJSON,
} from './QuantityMemoryDto';

/**
 * 
 * @export
 * @interface VirtualMachineDto
 */
export interface VirtualMachineDto {
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineDto
     */
    poolId: string;
    /**
     * 
     * @type {QuantityMemoryDto}
     * @memberof VirtualMachineDto
     */
    ram: QuantityMemoryDto;
    /**
     * 
     * @type {QuantityMemoryDto}
     * @memberof VirtualMachineDto
     */
    storage: QuantityMemoryDto;
    /**
     * 
     * @type {QuantityVCPUDto}
     * @memberof VirtualMachineDto
     */
    vcpu: QuantityVCPUDto;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof VirtualMachineDto
     */
    meta: { [key: string]: string; };
}

/**
 * Check if a given object implements the VirtualMachineDto interface.
 */
export function instanceOfVirtualMachineDto(value: object): value is VirtualMachineDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('poolId' in value) || value['poolId'] === undefined) return false;
    if (!('ram' in value) || value['ram'] === undefined) return false;
    if (!('storage' in value) || value['storage'] === undefined) return false;
    if (!('vcpu' in value) || value['vcpu'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function VirtualMachineDtoFromJSON(json: any): VirtualMachineDto {
    return VirtualMachineDtoFromJSONTyped(json, false);
}

export function VirtualMachineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualMachineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'poolId': json['pool_id'],
        'ram': QuantityMemoryDtoFromJSON(json['ram']),
        'storage': QuantityMemoryDtoFromJSON(json['storage']),
        'vcpu': QuantityVCPUDtoFromJSON(json['vcpu']),
        'meta': json['meta'],
    };
}

export function VirtualMachineDtoToJSON(value?: VirtualMachineDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'pool_id': value['poolId'],
        'ram': QuantityMemoryDtoToJSON(value['ram']),
        'storage': QuantityMemoryDtoToJSON(value['storage']),
        'vcpu': QuantityVCPUDtoToJSON(value['vcpu']),
        'meta': value['meta'],
    };
}

